# ═══════════════════════════════════════════════════════════════
# FreshTrack AI Review Configuration
# Автоматическое ревью кода с помощью LLM
# ═══════════════════════════════════════════════════════════════

llm:
  # Провайдер LLM: OPENAI | GEMINI | CLAUDE
  # GEMINI - бесплатный! Получить ключ: https://aistudio.google.com/apikey
  provider: GEMINI
  
  meta:
    model: gemini-1.5-flash
    max_tokens: 12000
    temperature: 0.3
  
  http_client:
    timeout: 120
    api_url: https://generativelanguage.googleapis.com/v1beta
    api_token: ${GEMINI_API_KEY}

# ═══════════════════════════════════════════════════════════════
# VCS Integration (GitHub)
# ═══════════════════════════════════════════════════════════════
vcs:
  provider: GITHUB
  pipeline:
    owner: ${GITHUB_REPOSITORY_OWNER}
    repo: ${GITHUB_REPOSITORY_NAME}
    pull_number: ${GITHUB_PR_NUMBER}
  http_client:
    timeout: 120
    api_url: https://api.github.com
    api_token: ${GITHUB_TOKEN}

# ═══════════════════════════════════════════════════════════════
# Prompt Configuration
# ═══════════════════════════════════════════════════════════════
prompt:
  # Контекстные переменные для промптов
  context:
    project_name: "FreshTrack"
    project_type: "Inventory Management System"
    stack: "React + Express.js + PostgreSQL"
    language: "JavaScript/TypeScript"
  
  context_placeholder: "<<{value}>>"
  normalize_prompts: true
  
  # Inline Review промпты
  inline_prompt_files:
    - .ai-review/prompts/inline.md
  
  system_inline_prompt_files:
    - .ai-review/prompts/system_inline.md
  
  include_inline_system_prompts: true
  
  # Context Review промпты
  context_prompt_files:
    - .ai-review/prompts/context.md
  
  system_context_prompt_files:
    - .ai-review/prompts/system_context.md
  
  include_context_system_prompts: true
  
  # Summary Review промпты
  summary_prompt_files:
    - .ai-review/prompts/summary.md
  
  system_summary_prompt_files:
    - .ai-review/prompts/system_summary.md
  
  include_summary_system_prompts: true

# ═══════════════════════════════════════════════════════════════
# Review Settings
# ═══════════════════════════════════════════════════════════════
review:
  # Режим анализа диффов
  mode: FULL_FILE_DIFF
  
  # Теги для AI-комментариев
  inline_tag: "#ai-review"
  summary_tag: "#ai-review-summary"
  
  # Контекстные строки вокруг изменений
  context_lines: 10
  
  # Файлы для игнорирования
  ignore_changes:
    - "*.md"
    - "*.txt"
    - "*.json"
    - "*.lock"
    - "package-lock.json"
    - "yarn.lock"
    - "*.svg"
    - "*.png"
    - "*.jpg"
    - "*.ico"
    - "*.woff*"
    - "dist/*"
    - "node_modules/*"
    - ".github/*"
    - "docs/*"
    - "uploads/*"
    - "*.test.js"
    - "*.spec.js"
  
  # Лимиты комментариев
  max_inline_comments: 20
  max_context_comments: 10

# ═══════════════════════════════════════════════════════════════
# Logging & Artifacts
# ═══════════════════════════════════════════════════════════════
logger:
  level: INFO
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {extra[logger_name]} | {message}"

artifacts:
  llm_dir: ./artifacts/ai-review
  llm_enabled: false
